list:
    accept: ['text/html', 'application/json']
    template: "user/list.html.twig"

new:
    accept: ['text/html']
    template: "user/new.html.twig"

create:
    accept: ['text/html', 'application/json']
    template: "user/new.html.twig"

show:
    accept: ['text/html', 'application/json']
    template: "user/show.html.twig"

edit:
    accept: ['text/html']
    template: "user/edit.html.twig"

update:
    accept: ['text/html', 'application/json']
    template: "user/edit.html.twig"

remove:
    accept: ['text/html']
    template: "user/remove.html.twig"

delete:
    accept: ['text/html', 'application/json']
