app:
    resource: "@AppBundle/Controller/"
    type:     annotation

security:
    resource: "config/routing/security.yml"

usuarios:
    resource: "config/routing/usuario.yml"
    prefix: /usuarios
