app:
    resource: "@AppBundle/Controller/"
    type:     annotation

security:
    resource: "config/routing/security.yml"

user:
    resource: "config/routing/user.yml"
    prefix: /users

groups:
    resource: "config/routing/group.yml"
    prefix: /groups
