security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        db_provider:
            entity:
                class: AppBundle\Entity\Usuario
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            logout:
                path:     /logout
            anonymous:    true
            guard:
                authenticators:
                    - app.security.form_authenticator
                    - app.security.token_authenticator
                entry_point: app.security.form_authenticator

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, role: IS_AUTHENTICATED_FULLY }
