imports:
    - { resource: "../Resources/config/services/eventos.yml" }

parameters:

services:
#Factories
    app.response.response_factory:
        class: AppBundle\Response\ResponseFactory
        arguments: ['@service_container']
#Authenticators
    app.security.form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        autowire: true

    app.security.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        autowire: true
