group_list:
    path:     /
    defaults: { _controller: "AppBundle:Group:list" }
    methods:  [GET]

group_new:
    path:     /new
    defaults: { _controller: "AppBundle:Group:new" }
    methods:  [GET]

group_create:
    path:     /create
    defaults: { _controller: "AppBundle:Group:create" }
    methods:  [POST]

group_show:
    path:     /{id}
    defaults: { _controller: "AppBundle:Group:show" }
    methods:  [GET]

group_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Group:edit" }
    methods:  [GET]

group_update:
    path:     /{id}
    defaults: { _controller: "AppBundle:Group:update" }
    methods:  [PUT]

group_remove:
    path:     /{id}/remove
    defaults: { _controller: "AppBundle:Group:remove" }
    methods:  [GET]

group_delete:
    path:     /{id}
    defaults: { _controller: "AppBundle:Group:delete" }
    methods:  [DELETE]
