user_list:
    path:     /
    defaults: { _controller: "AppBundle:User:list" }
    methods:  [GET]

user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }
    methods:  [GET]

user_create:
    path:     /create
    defaults: { _controller: "AppBundle:User:create" }
    methods:  [POST]

user_show:
    path:     /{id}
    defaults: { _controller: "AppBundle:User:show" }
    methods:  [GET]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET]

user_update:
    path:     /{id}
    defaults: { _controller: "AppBundle:User:update" }
    methods:  [PUT]

user_remove:
    path:     /{id}/remove
    defaults: { _controller: "AppBundle:User:remove" }
    methods:  [GET]

user_delete:
    path:     /{id}
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  [DELETE]
