services:
#Subscribers
    app.subscriber.exception:
        class: AppBundle\EventSubscriber\ExceptionSubscriber
        arguments: ['@app.response.response_factory']
        tags:
            - { name: kernel.event_subscriber }

    app.subscriber.view_response:
        class: AppBundle\EventSubscriber\ViewResponseSubscriber
        arguments: ['@app.response.response_factory']
        tags:
            - { name: kernel.event_subscriber }
